name: Process Recurring Transactions

on:
  schedule:
    # Runs at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  process-transactions:
    runs-on: ubuntu-latest
    steps:
      - name: Call cron endpoint
        run: |
          curl --request POST \
            --url '${{ secrets.APP_URL }}/api/cron' \
            --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'
